[Settings]
#This is a retriever5 version, added output_folder_path
input_folder_path = /Users/jwozniak/Downloads/EDF_LOANER/08
output_folder_path = /Users/jwozniak/Downloads/EDF_LOANER

zipped = True
extension = h5
# columns can be either All, or a comma separated list of columns. If specifying columns, column time has to be named
#columns = time, 12CO2, 13CO2, H2O, Delta_Raw_iCO2
columns = ALARM_STATUS, CH4, CavityPressure, CavityTemp, DATE_TIME, DasTemp, EtalonTemp, FRAC_HRS_SINCE_JAN1, H2CO, H2O, INST_STATUS, MPVPosition, OutletValve, WarmBoxTemp, species, F_EtOcal, F_EtOspl, F_HCHOcal, F_HCHOspl, time, timestamp, F_OUTbyp, F_ZTcond
#columns = All
# Any of the dates can be left empty, use YYYY-MM-DD HH:MM:ss formatting. 
date_from = 2023-08-10 00:00:00
#date_to = 2023-04-13 22:30:00
date_to = 2023-08-15 00:00:00
# sync_interval is a time interval in miliseconds
sync_interval = 2000
output_filename = timestamp_bin_
export_parquet = False
export_csv = False
export_hdf5 = True
