[Settings]
#This is a retriever5 version, added output_folder_path
input_folder_path = /Users/jwozniak/Library/CloudStorage/OneDrive-Picarro,Inc/PROJECTS/CLOSED LOOP TESTS/Data _for_retriever
output_folder_path = /Users/jwozniak/Library/CloudStorage/OneDrive-Picarro,Inc/PROJECTS/CLOSED LOOP TESTS

zipped = True
extension = h5
# columns can be either All, or a comma separated list of columns. If specifying columns, column time has to be named
#columns = time, 12CO2, 13CO2, H2O, Delta_Raw_iCO2
columns = CH4, CO2, N2O, NH3, CavityPressure, CavityTemp, DATE_TIME, FRAC_HRS_SINCE_JAN1, H2O, INST_STATUS, OutletValve, time, timestamp, ALI_FLOW, ALI_PRESSURE
#columns = All
# Any of the dates can be left empty, use YYYY-MM-DD HH:MM:ss formatting. 
date_from = 
#date_to = 2023-04-13 22:30:00
date_to = 
# sync_interval is a time interval in miliseconds
sync_interval = 500
output_filename = closed_loop_tests_RAW
export_parquet = False
export_csv = False
export_hdf5 = True
